apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: obox-test-data-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: obox-test-data-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 300
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80