apiVersion: v1
kind: Secret
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  labels:
    app: service
    name: {{cookiecutter.component_id | jsonify}}-secret
type: Opaque
# data:
    # K8S_DB_sn2_PASSWORD_oms_adm: {{K8S_DB_sn2_PASSWORD_oms_adm}}
#    DB_sni_PASSWORD_sni_guest: {{DB_sni_PASSWORD_sni_guest}}
