apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstag
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Backstag
    email: backstag@example.com
    picture: https://example.com/groups/backstag.jpeg
  parent: infrastructur
  children: [team-a, team-sni]
