apiVersion: v1
kind: ConfigMap
metadata:
  name: obox-test-data-service-logback
  labels:
    name: obox-test-data-service
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="60 seconds">
    <jmxConfigurator />
    <appender name="consoleAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
    </appender>
    <logger name="com.schneider" level="INFO" />
    <root level="INFO">
        <appender-ref ref="consoleAppender" />
    </root>
    </configuration>
