apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  labels:
    app: service
    name: {{cookiecutter.component_id | jsonify}}-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 300
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: {{cookiecutter.component_id | jsonify}}
      app: service
  template:
    metadata:
      labels:
        name: {{cookiecutter.component_id | jsonify}}
        app: service
    spec:
      containers:
      - name: {{cookiecutter.component_id | jsonify}}
        image: nexus-url/unt/{{cookiecutter.component_id | jsonify}}:101
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 550Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: {{cookiecutter.component_id | jsonify}}
        - secretRef:
            name: {{cookiecutter.component_id | jsonify}}
        imagePullPolicy: Always
        volumeMounts:
          - name: logback
            mountPath: /etc/config/springboot
      volumes:
        - name: logback
          configMap:
            items:
              - key: logback.xml
                path: logback.xml
            name: {{cookiecutter.component_id | jsonify}}-logback
      imagePullSecrets:
      - name: registry-secret
