apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: service
    name: {{cookiecutter.component_id | jsonify}}-route
  name: {{cookiecutter.component_id | jsonify}}
spec:
  host: {{cookiecutter.component_id | jsonify}}-unt-test.ccc
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: {{cookiecutter.component_id | jsonify}}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
      host: {{cookiecutter.component_id | jsonify}}-{{ENV_SHORT_NAME}}-unt-test.ccc
      routerName: router
      wildcardPolicy: None
