apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: service
    name: obox-test-data-service-route
  name: obox-test-data-service
spec:
  host: obox-test-data-service-{{ENV_SHORT_NAME}}-{{NAMESPACE}}.{{OCP_URL_SUFFIX}}
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: obox-test-data-service
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
      host: obox-test-data-service-{{ENV_SHORT_NAME}}-{{NAMESPACE}}.{{OCP_URL_SUFFIX}}
      routerName: router
      wildcardPolicy: None
